const STORAGE_KEY="a4p_platform_v5";const HUB_RESULTS_KEY="a4p_hub_results";
function readData(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||{clubs:[],teams:[],players:[],results:[],links:[]}}catch(e){return{clubs:[],teams:[],players:[],results:[],links:[]}}}
function saveData(d){localStorage.setItem(STORAGE_KEY,JSON.stringify(d))}
function uid(p="id"){return p+"_"+Math.random().toString(36).slice(2,10)}
function getParam(n){return new URLSearchParams(window.location.search).get(n)}
function average(a){return a.length?Math.round(a.reduce((x,y)=>x+y,0)/a.length):0}
function normalizeLikert(v){return Math.round(((Number(v)-1)/4)*100)}
function chooseCMPProfile(dim){const g=average([dim.confiance,dim.regulation,dim.engagement,dim.stabilite]);if(g>=70&&dim.confiance>=65&&dim.regulation>=65&&dim.engagement>=65&&dim.stabilite>=65)return CMP_PROFILES["CMP-1"];if(dim.engagement>=70&&dim.regulation<60)return CMP_PROFILES["CMP-2"];if(dim.engagement>=60&&dim.confiance<60)return CMP_PROFILES["CMP-3"];if(g<50||(dim.confiance<50&&dim.regulation<50))return CMP_PROFILES["CMP-5"];return CMP_PROFILES["CMP-4"]}
function formatAlert(score,dim){const weak=Object.values(dim).filter(v=>v<40).length;if(score<45||weak>=2)return{label:"Alerte rouge",cls:"danger",emoji:"🔴"};if(score<55||Object.values(dim).some(v=>v<45))return{label:"Vigilance",cls:"warn",emoji:"🟠"};return{label:"Stable",cls:"ok",emoji:"🟢"}}
function ensureSeed(){const d=readData();if(d.clubs.length)return;const clubId=uid("club"),teamId=uid("team");d.clubs.push({id:clubId,name:"Exemple A4P Club",created_at:new Date().toISOString()});d.teams.push({id:teamId,club_id:clubId,name:"U18",sport:"Rugby",category:"U18",expected_players:18,coach_name:"Coach Exemple",created_at:new Date().toISOString()});[["Lucas","Martin",[56,44,75,81]],["Pierre","Dubois",[68,60,74,69]],["Tom","Bernard",[41,39,62,43]],["Hugo","Morel",[72,64,71,68]]].forEach(p=>{const pid=uid("player");d.players.push({id:pid,team_id:teamId,first_name:p[0],last_name:p[1],role:"",created_at:new Date().toISOString()});const dims={confiance:p[2][0],regulation:p[2][1],engagement:p[2][2],stabilite:p[2][3]},score_global=average([dims.confiance,dims.regulation,dims.engagement,dims.stabilite]),profile=chooseCMPProfile(dims);d.results.push({id:uid("res"),team_id:teamId,player_id:pid,module:"CMP",date:new Date().toISOString().slice(0,10),score_global,dimensions:dims,profil_code:profile.code,profil_nom:profile.nom,summary:profile.resume})});saveData(d)}
function exportLatestCMPToHub(){const d=readData();const latest=[...d.results].filter(r=>r.module==="CMP").sort((a,b)=>String(b.date).localeCompare(String(a.date)))[0];if(!latest)return;let hub={};try{hub=JSON.parse(localStorage.getItem(HUB_RESULTS_KEY))||{}}catch(e){}hub.CMP={test:"CMP",profil_code:latest.profil_code,profil_nom:latest.profil_nom,score_global:latest.score_global,dimensions:latest.dimensions,summary:latest.summary,timestamp:new Date().toISOString()};localStorage.setItem(HUB_RESULTS_KEY,JSON.stringify(hub))}
function teamStats(teamId){const d=readData(),team=d.teams.find(t=>t.id===teamId),players=d.players.filter(p=>p.team_id===teamId),results=d.results.filter(r=>r.team_id===teamId&&r.module==="CMP"),dims={confiance:average(results.map(r=>r.dimensions.confiance)),regulation:average(results.map(r=>r.dimensions.regulation)),engagement:average(results.map(r=>r.dimensions.engagement)),stabilite:average(results.map(r=>r.dimensions.stabilite))},score=average(results.map(r=>r.score_global)),alerts=results.filter(r=>formatAlert(r.score_global,r.dimensions).cls!=="ok").length;const profiles={};results.forEach(r=>profiles[r.profil_code]=(profiles[r.profil_code]||0)+1);let dominant="-",max=0;Object.entries(profiles).forEach(([k,v])=>{if(v>max){max=v;dominant=k}});return{team,players,results,dims,score,alerts,dominant}}
function renderRadar(id,dims,label="Equipe"){const c=document.getElementById(id);if(!c||typeof Chart==="undefined")return;new Chart(c,{type:"radar",data:{labels:["Confiance","Régulation","Engagement","Stabilité"],datasets:[{label,data:[dims.confiance,dims.regulation,dims.engagement,dims.stabilite],backgroundColor:"rgba(22,58,99,0.20)",borderColor:"#163a63",borderWidth:2,pointBackgroundColor:"#163a63"}]},options:{responsive:true,maintainAspectRatio:true,scales:{r:{min:0,max:100,ticks:{stepSize:20},pointLabels:{font:{size:12}}}},plugins:{legend:{display:false}}}})}
function renderLine(id,points){const c=document.getElementById(id);if(!c||typeof Chart==="undefined")return;new Chart(c,{type:"line",data:{labels:points.map(p=>p.label),datasets:[{label:"Evolution score moyen",data:points.map(p=>p.value),borderColor:"#163a63",backgroundColor:"rgba(22,58,99,.15)",tension:.25,fill:true}]},options:{responsive:true,plugins:{legend:{display:false}},scales:{y:{min:0,max:100}}}})}
function makePassationURL(teamId,module="cmp"){const url=new URL(window.location.origin+window.location.pathname.replace(/[^/]+$/,"")+"passation.html");url.searchParams.set("team_id",teamId);url.searchParams.set("module",module.toUpperCase());return url.toString()}